on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Rmd Site
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        path: current
        token: ${{ secrets.token }}
    - name: Checkout current repo
      uses: actions/checkout@v2
      with:
        repository: 'averissimo/website'
        path: website
        token: ${{ secrets.token }}
    - name: Get current directory and files
      run: |
        pwd
        ls website
        ls current
    - name: Build html
      id: build
      run: |
        cd website
        npm install -g yarn
        yarn install
        yarn build

    - name: Update site
      id: update
      run: |
        cd current
        rm -rf *
        cp -r ../repo/dist/* .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update site (automatic)" || echo "Nothing to update"
        git status

    - name: Push changes
      uses: ad-m/github-push-action@fe38f0a751bf9149f0270cc1fe20bf9156854365
      with:
        directory: current
        repository: averissimo/averissimo.github.io
        github_token: ${{ secrets.token }}
